### ISSUE TITLE
SHK: Patrick Kubat in die Org hinzufügen

### ISSUE THREAD

**Issue by senycorp** [wi-kuk/Proco-Daily-Business#10]
Hi,

der neue SHK sollte ebenfalls Zugriff auf die Org haben. Sein Github-Username lautet: patkubat

Es wäre vorzüglich, gediegen, ausgezeichnet, falls das heute noch möglich wäre :smile: :+1: :cake: :calendar:  .

VG

Selcuk

**Comment by WIKUK** [comment]
Done!

**Comment by senycorp** [comment]
Super dab
